version: "3.9"
services:
  api:
    container_name: welsh-academy
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: welsh-academy-db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      # - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  
volumes:
  api:
  db: